max-pages: 5
page-costs:
  2: 10
  3: 20
  4: 30
  5: 40

database:
  host: "localhost"
  port: "3307"
  name: "minecraft_storage"
  user: "root"
  password: ""

currency-item:
  material: "SMALL_AMETHYST_BUD"
  name: "§5§lAndermant"
