name: storageplugin
version: '1.0-SNAPSHOT'
main: com.maks.storageplugin.Main
api-version: '1.20'
commands:
  storage:
    description: Opens the player storage
    usage: /storage
    permission: playerstorage.use
    permission-message: "You do not have permission to use this command."